<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYG0NwcR\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYG0NwcR/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYG0NwcR.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYG0NwcR\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerYG0NwcR\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'YG0NwcR',
    'container.build_id' => '050cb59a',
    'container.build_time' => 1593088773,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYG0NwcR');
