<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGrXBkID\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGrXBkID/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGrXBkID.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGrXBkID\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerGrXBkID\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'GrXBkID',
    'container.build_id' => 'c2f8bf61',
    'container.build_time' => 1593611675,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGrXBkID');
